'use strict';
const path = require('path');
const PdfPrinter = require('pdfmake');
const jwt  = require('jsonwebtoken');

const PROJECTS = [
  { num: 1, name: 'Top Golf',      sheetId: '1yigtLymmZ7UEI2JO9McSlcBd1PXs8_SixVcrEul-cRw', gid: 0 },
  { num: 2, name: 'OT Sky Palace', sheetId: '1IiznhN8XufPrj6ARQ_Y7JQx-6BWR_eWRHjjaWjDBDBs', gid: 0 },
  { num: 3, name: 'ORLA Towers',   sheetId: '1SqpbGpQGIp5szLI7qF9s7CJJcDCnBiwOrxiKAAeJ3-Y', gid: 0 },
  { num: 4, name: 'Abaad Wood',    sheetId: '1HIswdQy7iyESzys_2_wrmFDg2vX4yqsIWR1vx8kc2Qo', gid: 0 },
  { num: 5, name: 'DSA',           sheetId: '1v--XBPFdO8cEivKwlgUZVNPrTH-CLQxXWH1IUN299C0', gid: 0 },
  { num: 6, name: 'Al-Badia',      sheetId: '1q734Gm_y_8ktlfG3ay1LDm_7EfBlFMHSzczl7WlKGXg', gid: 0 },
  { num: 7, name: 'H2R',           sheetId: '15QDe20Car2gYTfSotQ0ATTRBQaZ94CSsr4Ci0Fc2HTM', gid: 0 },
];
const DAYS_TO_SHOW = 5;
const DARK_BG='#1F3864',DARK_FG='#FFFFFF',ACCENT_BG='#2E5A99',SECT_BG='#D9E1F2',ALT_BG='#F0F4FB',ABSENT_BG='#FFD7D7',PRESENT_BG='#E8F5E9',BODY_SZ=7.5,HEAD_SZ=8;
const fonts={DejaVu:{normal:path.join(__dirname,'_master','fonts','DejaVuSans.ttf'),bold:path.join(__dirname,'_master','fonts','DejaVuSans-Bold.ttf'),italics:path.join(__dirname,'_master','fonts','DejaVuSans-Oblique.ttf'),bolditalics:path.join(__dirname,'_master','fonts','DejaVuSans-BoldOblique.ttf')}};
const printer=new PdfPrinter(fonts);
function fetchText(url){return new Promise(resolve=>{const mod=url.startsWith('https')?require('https'):require('http');mod.get(url,{headers:{'User-Agent':'Mozilla/5.0'}},res=>{if(res.statusCode>=300&&res.statusCode<400&&res.headers.location)return fetchText(res.headers.location).then(resolve);if(res.statusCode===403||res.statusCode===404||res.statusCode===401){res.resume();return resolve(null);}let data='';res.on('data',c=>data+=c);res.on('end',()=>resolve(data));}).on('error',()=>resolve(null));});}
function parseCSVLine(line){const out=[];let cur='';let inQ=false;for(const ch of line){if(ch==='"'){inQ=!inQ;}else if(ch===','&&!inQ){out.push(cur);cur='';}else{cur+=ch;}}out.push(cur);return out.map(v=>v.trim());}
function parseCSV(text){return(text||'').replace(/

/g,'
').replace(/
/g,'
').split('
').map(parseCSVLine);}
function getWorkingDays(n){const days=[];const d=new Date();d.setDate(d.getDate()-1);while(days.length<n){if(d.getDay()!==0){const month=d.toLocaleString('en-US',{month:'short'});const dayNum=String(d.getDate()).padStart(2,'0');const dayName=d.toLocaleString('en-US',{weekday:'short'});days.unshift({label:month+' '+dayNum,dayName,year:d.getFullYear()});}d.setDate(d.getDate()-1);}return days;}
function isDateCell(cell){const top=(cell||'').split('
')[0].trim();return /^(Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)s+d{1,2}$/.test(top);}
function cellTopLine(cell){return(cell||'').split('
')[0].trim();}
function normCell(raw){const v=(raw||'').trim();if(!v||v==='-'||v==='—'||v==='–')return'—';if(/^a$/i.test(v)||/^absent$/i.test(v))return'Absent';return v;}
function parseKpiCsv(csv,workingDays){const rows=parseCSV(csv);if(rows.length<5)return null;const coordHdrIdx=rows.findIndex(r=>(r[0]||'').toLowerCase().trim()==='coordinator name');if(coordHdrIdx<0)return null;const hdr=rows[coordHdrIdx];const dateColMap={};for(let i=0;i<hdr.length;i++){if(isDateCell(hdr[i]))dateColMap[cellTopLine(hdr[i])]=i;}const dayMeta=workingDays.map(d=>({...d,colIdx:dateColMap[d.label]??-1}));let coordDataIdx=coordHdrIdx+1;while(coordDataIdx<rows.length&&!(rows[coordDataIdx][0]||'').trim())coordDataIdx++;const coordRow=rows[coordDataIdx]||[];const coordName=(coordRow[0]||'').trim();const coordTotal=(coordRow[2]||'').trim();const coordDaily=dayMeta.map(d=>d.colIdx>=0?normCell(coordRow[d.colIdx]):'—');const sections=[];const isModelerHeader=r=>/modeler[s]? name/i.test(r[0]||'')||/modeller[s]? name/i.test(r[0]||'');for(let i=coordDataIdx+1;i<rows.length;i++){if(!isModelerHeader(rows[i]))continue;let titleIdx=i+1;while(titleIdx<rows.length&&!(rows[titleIdx]&&(rows[titleIdx][0]||'').trim()))titleIdx++;const titleText=rows[titleIdx]?(rows[titleIdx][0]||'').trim():'';const sectionType=/sheet/i.test(titleText)?'sheet':/parameter/i.test(titleText)?'parameter':'model';const dataRows=[];let di=titleIdx+1;while(di<rows.length){const r=rows[di];const name=(r[0]||'').trim();if(!name){di++;continue;}if(isModelerHeader(r))break;const mgr=(r[1]||'').trim();const pkg=(r[2]||'').trim();const daily=dayMeta.map(d=>d.colIdx>=0?normCell(r[d.colIdx]):'—');dataRows.push({name,manager:mgr,pkg,daily});di++;}if(dataRows.length>0){sections.push({type:sectionType,title:titleText,dataRows});}i=di-1;}const mgMap={};sections.forEach(s=>s.dataRows.forEach(r=>{if(r.manager)mgMap[r.manager]=(mgMap[r.manager]||0)+1;}));const pm=Object.entries(mgMap).sort((a,b)=>b[1]-a[1])[0]?.[0]||'';return{coordName,coordTotal,coordDaily,pm,sections};}
function buildCover(projects,workingDays,reportId){const first=workingDays[0];const last=workingDays[workingDays.length-1];const today=new Date();const issueDateStr=today.toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric'});const dateRange=workingDays.length===1?first.label+' '+first.dayName+', '+first.year:first.label+' & '+last.label+', '+last.year;const dayRange=workingDays.map(d=>d.dayName).join(' · ');const projList=[];projects.forEach((p,i)=>{const d=p._parsed;projList.push({columns:[{text:String(p.num),bold:true,fontSize:13,color:DARK_BG,width:28,margin:[0,4,0,0]},{stack:[{text:p.name,bold:true,fontSize:12,color:DARK_BG,margin:[0,0,0,4]},{columns:[{stack:[{text:'COORDINATOR',fontSize:6.5,color:'#999999',bold:true},{text:d?d.coordName||'—':'—',fontSize:9,bold:true,color:'#333333'}],width:120},{stack:[{text:'PROJECT MANAGER',fontSize:6.5,color:'#999999',bold:true},{text:d?d.pm||'—':'—',fontSize:9,bold:true,color:'#333333'}]}]}]}],margin:[0,8,0,8]});if(i<projects.length-1){projList.push({canvas:[{type:'line',x1:0,y1:0,x2:500,y2:0,lineWidth:0.4,lineColor:'#DDDDDD'}]});}});return[{text:'CONFIDENTIAL  ·  INTERNAL DISTRIBUTION',fontSize:8,color:'#999999',alignment:'center',margin:[0,0,0,3]},{text:'Report ID  ·  '+reportId,fontSize:8,color:'#999999',alignment:'center',margin:[0,0,0,18]},{table:{widths:['*',165],body:[[{stack:[{text:'PROJECT PORTFOLIO',fontSize:10,bold:true,color:DARK_FG,margin:[0,0,0,4]},{text:'KPI Report',fontSize:30,bold:true,color:DARK_FG,margin:[0,0,0,8]},{text:'Portfolio delivery performance · '+projects.length+' active projects',fontSize:9.5,color:'#BBCCDD'}],fillColor:DARK_BG,margin:[20,18,12,18]},{stack:[{text:'REPORTING WINDOW',fontSize:6.5,bold:true,color:'#BBBBBB',margin:[0,0,0,2]},{text:dateRange,fontSize:10,bold:true,color:DARK_FG,margin:[0,0,0,1]},{text:dayRange,fontSize:8,color:'#AAAAAA',margin:[0,0,0,14]},{text:'ISSUE DATE',fontSize:6.5,bold:true,color:'#BBBBBB',margin:[0,0,0,2]},{text:issueDateStr,fontSize:10,bold:true,color:DARK_FG,margin:[0,0,0,1]},{text:'End-of-day snapshot',fontSize:8,color:'#AAAAAA',margin:[0,0,0,14]},{text:'PROJECTS COVERED',fontSize:6.5,bold:true,color:'#BBBBBB',margin:[0,0,0,2]},{text:projects.length+' projects · 1 portfolio',fontSize:10,bold:true,color:DARK_FG}],fillColor:ACCENT_BG,margin:[14,18,14,18]}]]},layout:'noBorders',margin:[0,0,0,20]},...projList,{text:'Generated '+issueDateStr+'  ·  Data Analyst',fontSize:7.5,color:'#888888',alignment:'center',margin:[0,20,0,0]}];}
function buildKpiTable(section,dayMeta){const sectionLabel=section.type==='sheet'?'Sheet KPI':section.type==='parameter'?'Parameter KPI':'Model KPI';const hdrRow=[{text:'Name',style:'kth'},{text:'Package / Manager',style:'kth'},...dayMeta.map(d=>({text:d.label+'
'+d.dayName,style:'kth'}))];const bodyRows=section.dataRows.map((r,i)=>{const rowBg=i%2===0?'#FFFFFF':ALT_BG;return[{text:r.name,style:'ktd',fillColor:rowBg},{text:r.pkg||r.manager||'-',style:'ktd',fillColor:rowBg,color:'#555555'},...r.daily.map(v=>{const isAbsent=v==='Absent';const isEmpty=v==='—'||v==='-';const hasCount=!isAbsent&&!isEmpty;const fill=isAbsent?ABSENT_BG:hasCount?PRESENT_BG:rowBg;const color=isAbsent?'#CC0000':hasCount?'#1A6B1A':'#AAAAAA';return{text:v,style:'ktd',fillColor:fill,alignment:'center',bold:hasCount,color};})];});const dayW=Math.max(38,Math.min(55,Math.floor(230/dayMeta.length)));const colWidths=[105,100,...dayMeta.map(()=>dayW)];return{stack:[{table:{widths:['*'],body:[[{text:'ℹ  '+sectionLabel,bold:true,fontSize:8.5,color:DARK_BG,margin:[6,4,6,4]}]]},layout:'noBorders',fillColor:SECT_BG,margin:[0,10,0,0]},{table:{headerRows:1,widths:colWidths,body:[hdrRow,...bodyRows]},layout:{hLineWidth:()=>0.5,vLineWidth:()=>0.5,hLineColor:()=>'#CCCCCC',vLineColor:()=>'#CCCCCC'}}]};}
function buildProjectPage(proj,dayMeta){const data=proj._parsed;const coordName=data?data.coordName||'—':'—';const coordDaily=data?data.coordDaily:dayMeta.map(()=>'—');const elements=[];elements.push({table:{widths:['*','auto'],body:[[{stack:[{text:proj.num+'. '+proj.name,fontSize:22,bold:true,color:DARK_BG},{text:coordName,fontSize:13,color:'#444444',margin:[0,3,0,0]},{text:'Coordinator',fontSize:8.5,color:'#888888'}],margin:[0,6,0,6]},{table:{widths:dayMeta.map(()=>'*'),body:[dayMeta.map(d=>({text:d.label+'
'+d.dayName,fontSize:7,bold:true,color:DARK_FG,alignment:'center',fillColor:ACCENT_BG,margin:[4,3,4,3]})),coordDaily.map(v=>{const isA=v==='Absent';const empty=v==='—';return{text:v,fontSize:14,bold:true,color:isA?'#CC0000':empty?'#BBBBBB':'#1A6B1A',fillColor:isA?ABSENT_BG:'#FFFFFF',alignment:'center',margin:[4,4,4,4]};})]},layout:{hLineWidth:()=>0.5,vLineWidth:()=>0.5,hLineColor:()=>'#DDDDDD',vLineColor:()=>'#DDDDDD'},margin:[0,6,0,6]}]]},layout:'noBorders',margin:[0,0,0,2]});elements.push({canvas:[{type:'line',x1:0,y1:0,x2:545,y2:0,lineWidth:1.5,lineColor:DARK_BG}],margin:[0,0,0,4]});if(!data||!data.sections||data.sections.length===0){elements.push({stack:[{text:'⚠  Sheet not yet published',fontSize:10,bold:true,color:'#CC7700',margin:[0,12,0,4]},{text:'To enable live data for this project, publish the KPI tab:
1. Open the project sheet in Google Sheets
2. File → Share → Publish to web
3. Select the "KPI" tab → Format: CSV → click Publish
4. No further action needed — the report will auto-update.',fontSize:8.5,color:'#666666',lineHeight:1.5}]});}else{data.sections.forEach(sec=>{elements.push(buildKpiTable(sec,dayMeta));});}return elements;}
function buildPdf(projects,workingDays,reportId){const today=new Date();const dateStr=today.toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric'});const first=workingDays[0];const last=workingDays[workingDays.length-1];const hdrRange=first.label+' & '+last.label+', '+last.year;const content=[];content.push(...buildCover(projects,workingDays,reportId));for(const proj of projects){content.push({text:'',pageBreak:'before'});for(const el of buildProjectPage(proj,workingDays))content.push(el);}return{pageSize:'A4',pageOrientation:'portrait',pageMargins:[25,50,25,45],content,header:(currentPage,pageCount)=>{if(currentPage===1)return{};return{columns:[{text:'KPI Report — Project Portfolio',fontSize:8,bold:true,color:DARK_BG,margin:[25,14,0,0]},{text:hdrRange+'  ·  '+reportId,fontSize:7,color:'#888888',alignment:'right',margin:[0,14,25,0]}]};},footer:(currentPage,pageCount)=>({columns:[{text:'Confidential  ·  Data Analyst',fontSize:7,color:'#888888',margin:[25,0,0,0]},{text:'Generated '+dateStr,fontSize:7,color:'#888888',alignment:'center'},{text:'Page '+currentPage+' of '+pageCount,fontSize:7,color:'#888888',alignment:'right',margin:[0,0,25,0]}]}),styles:{kth:{fontSize:HEAD_SZ,bold:true,fillColor:DARK_BG,color:DARK_FG,alignment:'center',margin:[2,3,2,3]},ktd:{fontSize:BODY_SZ,margin:[4,2,4,2]}},defaultStyle:{font:'DejaVu'}};}
module.exports=async(req,res)=>{res.setHeader('Access-Control-Allow-Origin','*');res.setHeader('Access-Control-Allow-Methods','GET, OPTIONS');res.setHeader('Access-Control-Allow-Headers','Content-Type, Authorization');if(req.method==='OPTIONS')return res.status(200).end();const token=(req.headers['authorization']||'').replace('Bearer ','').trim();try{jwt.verify(token,process.env.JWT_SECRET);}catch{return res.status(401).json({error:'Unauthorized'});}try{const workingDays=getWorkingDays(DAYS_TO_SHOW);const today=new Date();const reportId='KPI-'+today.getFullYear()+'-'+String(today.getMonth()+1).padStart(2,'0')+'-'+String(today.getDate()).padStart(2,'0');const enriched=await Promise.all(PROJECTS.map(async proj=>{const url='https://docs.google.com/spreadsheets/d/'+proj.sheetId+'/pub?gid='+proj.gid+'&single=true&output=csv';const csv=await fetchText(url);const parsed=csv?parseKpiCsv(csv,workingDays):null;return{...proj,_parsed:parsed};}));const docDef=buildPdf(enriched,workingDays,reportId);const doc=printer.createPdfKitDocument(docDef);res.setHeader('Content-Type','application/pdf');res.setHeader('Content-Disposition','inline; filename="'+reportId+'.pdf"');doc.pipe(res);doc.end();}catch(err){console.error('KPI report error:',err);res.status(500).json({error:err.message});}};
